spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url:
          - http://localhost:8888
        instance:
          prefer-ip : true
        period: 3000000

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always
    logfile.external-file: logs/client.log
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework.web: ERROR
    com:
      ga:
        adminclient: info
  file:
    name: logs/client.log
    path: logs